# Generated by Django 3.2.6 on 2021-09-11 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('budget_discord', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Code',
            fields=[
                ('code_id', models.AutoField(primary_key=True, serialize=False)),
                ('code', models.IntegerField()),
            ],
        ),
    ]
